export declare const isBrowser: boolean;
export declare const isDefined: <T = any>(val?: T | undefined) => val is T;
export declare const isBoolean: (val: any) => val is boolean;
export declare const isFunction: <T extends Function>(val: any) => val is T;
export declare const isNumber: (val: any) => val is number;
export declare const isString: (val: unknown) => val is string;
export declare const isWindow: (val: any) => val is Window;
export declare function isArray(value: any): value is any[];
export declare function isBase64(value: any): value is string;
export declare function isDate(value: any): value is Date;
export declare function isDateValid(value: any): value is Date;
export declare function isError(value: any): value is Error;
export declare function isSymbol(value: any): value is symbol;
export declare function isGuid(value: any): value is string;
export declare function isInfinity(value: any): value is number;
export declare function isNull(value: any): value is null;
export declare function isObject(value: any): value is object;
export declare function isPlainObject(value: any): value is object;
export declare function isRegExp(value: any): value is RegExp;
export declare function isUndefined(value: any): value is undefined;
export declare function isInstance<T extends new (...args: any[]) => any>(value: any, ctor: T): value is InstanceType<T>;
export declare const isURL: (url: string) => boolean;
